{% set name = "trame-server" %}
{% set version = "2.17.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trame-server-{{ version }}.tar.gz
  sha256: 1d6cbb0cd83f9073e895dfd32425ee29c751c8c3881dbb675bf8289c27058379

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - wslink >=1.9.0
    - more-itertools

test:
  imports:
    - trame_server
    - trame_server.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/trame-server/
  summary: Internal server side implementation of trame
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - banesullivan
    - jourdain
    - psavery
    - kwrobot
