{% set name = "trame-server" %}
{% set version = "2.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trame-server-{{ version }}.tar.gz
  sha256: f8e599a500e2eb4e90cc71802d5934beb68e6c4848846e5aa68e076df898b5de

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - wslink >=1.9.0

test:
  imports:
    - trame_server
    - trame_server.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/trame-server/
  summary: Internal server side implementation of trame
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - banesullivan
    - jourdain
    - psavery
    - kwrobot
