{% set name = "trame-server" %}
{% set version = "3.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ca4d8f6ba7e46b81bfe9e3f7eb83de3df9d35abb0f0921ba0cf00286a26756ea

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - python >={{ python_min }}
    - wslink >=2.2.1
    - more-itertools
    - trame-common >=1.2.3

test:
  imports:
    - trame_server
    - trame_server.utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/trame-server/
  summary: Internal server side implementation of trame
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - jourdain
    - psavery
    - kwrobot
