{% set name = "trame-server" %}
{% set version = "3.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trame-server-{{ version }}.tar.gz
  sha256: 03bdd81e0132fb55de7b493c7ebdc4c21f6b0003960bceb3adca258fc432211f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - wslink >=2
    - more-itertools

test:
  imports:
    - trame_server
    - trame_server.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/trame-server/
  summary: Internal server side implementation of trame
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - banesullivan
    - jourdain
    - psavery
    - kwrobot
